
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.plaf.DesktopPaneUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author rajan_gp8cx31
 */
public class ROOMREQ extends javax.swing.JInternalFrame {

    /**
     * Creates new form ROOMREQ
     */
    int check=0;
    JDesktopPane dekstoppane;

    public ROOMREQ(JDesktopPane dekstoppane) {
        initComponents();
        this.dekstoppane = dekstoppane;

        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        rButtonGeyserY = new javax.swing.JRadioButton();
        rButtonGeyserN = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rButtonWashroomY = new javax.swing.JRadioButton();
        rButtonWashroomN = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        bedChoicepass = new javax.swing.JComboBox<>();
        roomFieldpass = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel5.setText("GEYSER");

        buttonGroup2.add(rButtonGeyserY);
        rButtonGeyserY.setSelected(true);
        rButtonGeyserY.setText("YES");
        rButtonGeyserY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonGeyserYActionPerformed(evt);
            }
        });

        buttonGroup2.add(rButtonGeyserN);
        rButtonGeyserN.setText("NO");
        rButtonGeyserN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonGeyserNActionPerformed(evt);
            }
        });

        jLabel6.setText("COOLING FACILITY");

        jLabel7.setText("BEDS");

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "COOLER" }));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jButton1.setText("SHOW ROOMS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("WASHROOM ATTACHED");

        buttonGroup1.add(rButtonWashroomY);
        rButtonWashroomY.setSelected(true);
        rButtonWashroomY.setText("YES");

        buttonGroup1.add(rButtonWashroomN);
        rButtonWashroomN.setText("NO");
        rButtonWashroomN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonWashroomNActionPerformed(evt);
            }
        });

        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        showTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(showTable);

        jLabel1.setText("ROOMNO");

        jLabel2.setText("AVAILABLE BEDS");

        jButton2.setText("BOOK ROOM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bedChoicepass, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomFieldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bedChoicepass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rButtonWashroomY)
                                        .addGap(18, 18, 18)
                                        .addComponent(rButtonWashroomN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rButtonGeyserY)
                                        .addGap(18, 18, 18)
                                        .addComponent(rButtonGeyserN))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rButtonWashroomY)
                            .addComponent(rButtonWashroomN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rButtonGeyserY)
                            .addComponent(rButtonGeyserN)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rButtonGeyserYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonGeyserYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButtonGeyserYActionPerformed

    private void rButtonGeyserNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonGeyserNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButtonGeyserNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        check=1;
        String washroom = "";
        if (rButtonWashroomY.isSelected()) {
            washroom = "Yes";
        } else {
            washroom = "No";
        }
        String geyser = "";
        if (rButtonGeyserY.isSelected()) {
            geyser = "Yes";
        } else {
            geyser = "No";
        }
        String cooling = (String) combo1.getSelectedItem();
        String beds = (String) combo2.getSelectedItem();

        showData(washroom, geyser, cooling, beds);

    }//GEN-LAST:event_jButton1ActionPerformed

    void showData(String washroom, String geyser, String cooling, String beds) {

        Vector heading = new Vector();
        heading.add("Roomno");
        heading.add("Rent+food");
        heading.add("Rent");
        heading.add("Attachedwashroom");
        heading.add("Geyser");
        heading.add("Cooligitem");
        heading.add("Beds");

        try {
            //Establish Connection
//1. Initalize driver
            Class.forName("oracle.jdbc.OracleDriver");
//2. Create connection String
            String str = "jdbc:oracle:thin:@localhost:1522:";
//3. Open connection
            Connection con = DriverManager.getConnection(str, "Sharan", "pg");

            String sql = "select * from pgdata where attachedwashroom=? and geyser=? and coolingitem=? and beds=?";
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, washroom);
            ps.setString(2, geyser);
            ps.setString(3, cooling);
            ps.setString(4, beds);

            Vector data = new Vector();
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("roomno"));
                row.add(rs.getString("rentwithfood"));
                row.add(rs.getString("rentwithoutfood"));
                row.add(rs.getString("attachedwashroom"));
                row.add(rs.getString("geyser"));
                row.add(rs.getString("coolingitem"));
                row.add(rs.getString("beds"));

                data.add(row);

            }

            DefaultTableModel tm = new DefaultTableModel(data, heading);
            showTable.setModel(tm);

            con.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void rButtonWashroomNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonWashroomNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rButtonWashroomNActionPerformed

    private void showTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTableMouseClicked
        if(check==1)
        {jPanel1.setVisible(true);
        int row = showTable.getSelectedRow();
        TableModel tm = showTable.getModel();
        roomFieldpass.setText((String) tm.getValueAt(row, 0));

        String beds = (String) tm.getValueAt(row, 6);

        String roomno = roomFieldpass.getText();

        try {
            //1. Initalize driver
            Class.forName("oracle.jdbc.OracleDriver");
//2. Create connection String
            String str = "jdbc:oracle:thin:@localhost:1522:";
//3. Open connection
            Connection con = DriverManager.getConnection(str, "Sharan", "pg");

            //bedChoicepass.
            String sql2 = "select bedno from studentdata1 where roomno=? and status='Booked'";
            PreparedStatement ps2 = con.prepareStatement(sql2);
            ps2.setString(1, roomno);
            ResultSet rs3 = ps2.executeQuery();
            
            bedChoicepass.removeAllItems();

            String x = "";
            int a=0;
            int totalbed = Integer.parseInt(beds);
            
            ArrayList ar1=new ArrayList();
            ArrayList ar2=new ArrayList();
            for(int i=1;i<=totalbed;i++)
            {
                ar2.add(String.valueOf(i));
            }
            
            while (rs3.next()) {
                
                
                x = rs3.getString("bedno");
                a=Integer.parseInt(x);
                ar1.add(x);
            }
            
            if (a != 0)
            {for(int i=0;i<ar1.size();i++)
            {
                String sk=(String)ar1.get(i);
                if(ar2.contains(sk))
                {
                    ar2.remove(sk);
                }
            }
            bedChoicepass.removeAllItems();
            for(int i=0;i<ar2.size();i++)
            {
                String no=(String)ar2.get(i);
                
                
                bedChoicepass.addItem(no);
            }
            }
            else
             {
                int a1 = Integer.parseInt(beds);
                for (int i = 1; i <= a1; i++) {
                    String q;
                    q = String.valueOf(i);
                    bedChoicepass.addItem(q);
                    

                }
            }
         con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_showTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String roomnopass = roomFieldpass.getText();
        String bedspass = (String) bedChoicepass.getSelectedItem();
        if(bedspass==null)
        {
            JOptionPane.showMessageDialog(this,"SORRY NO ROOM AVAILABLE!!!");
        }
        else
        {
        STUREGFORM su = new STUREGFORM(roomnopass, bedspass);
        su.setVisible(true);
        dekstoppane.add(su);
        dispose();
        }

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bedChoicepass;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rButtonGeyserN;
    private javax.swing.JRadioButton rButtonGeyserY;
    private javax.swing.JRadioButton rButtonWashroomN;
    private javax.swing.JRadioButton rButtonWashroomY;
    private javax.swing.JTextField roomFieldpass;
    private javax.swing.JTable showTable;
    // End of variables declaration//GEN-END:variables
}
