
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rajan_gp8cx31
 */
public class SHOWDATA extends javax.swing.JInternalFrame {

    /**
     * Creates new form SHOWDATA
     */
    public SHOWDATA() {
        initComponents();
        showAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    void showAll() {
        

        Vector heading = new Vector();
        heading.add("StuId");
        heading.add("Roomno");
        heading.add("BedNo");
        heading.add("Name");
        heading.add("FatherName");
        heading.add("MotherName");
        heading.add("Gender");
        heading.add("Email");
        heading.add("ContactNo");
        heading.add("Address");
        heading.add("DateOfBooking");
        
        heading.add("Rent");
        heading.add("Status");
        heading.add("DateOfLeaving");

        try {
            //Establish Connection
//1. Initalize driver
            Class.forName("oracle.jdbc.OracleDriver");
//2. Create connection String
            String str = "jdbc:oracle:thin:@localhost:1522:";
//3. Open connection
            Connection con1 = DriverManager.getConnection(str, "Sharan", "pg");

            String sql = "select * from studentdata1 order by status";
            PreparedStatement ps = con1.prepareStatement(sql);
            Vector data = new Vector();
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString("studentid"));
                row.add(rs.getString("roomno"));
                row.add(rs.getString("bedno"));
                row.add(rs.getString("name"));
                row.add(rs.getString("fathername"));
                row.add(rs.getString("mothername"));
                row.add(rs.getString("gender"));
                row.add(rs.getString("email"));
                row.add(rs.getString("contactno"));
                row.add(rs.getString("address"));
                row.add(rs.getString("dateofbooking"));
                
                row.add(rs.getString("rent"));
                row.add(rs.getString("status"));
                row.add(rs.getString("dateofleaving"));

                data.add(row);

            }

            DefaultTableModel tm = new DefaultTableModel(data, heading);
            table.setModel(tm);
            con1.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
